; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:beermat_rev3]
platform_packages = platformio/framework-arduinoteensy @ symlink://../../framework-arduinoteensy-1.159
platform = teensy @ 5.0.0
board = teensymm
;lib_extra_dirs = ../../CDJ_Libs, ../../MyLibs      ; For LVGL 9
lib_extra_dirs = ../../CDJ_Libs                    ; For LVGL 8
lib_ignore = NativeEthernet
build_flags = ;-D LV_CONF_PATH="\"ian_lv_conf.h\""  ; For LVGL 9
              -D LV_CONF_INCLUDE_SIMPLE            ; For LVGL 8
              -D RDI_DEVELOPMENTS_REV3
              -D USB_DUAL_SERIAL
              ${common.build_flags}
board_build.f_cpu = 528000000L
monitor_port =  /dev/cu.usbmodem153596401  
board_build.ldscript = linkerScript/RDI_v6_saveITCM_heapSDRAM_setOCRAM_4M_8M_NOCACHE.ld   

[env:beermat_DB5]
platform_packages = platformio/framework-arduinoteensy @ symlink://../../framework-arduinoteensy-1.159
platform = teensy @ 5.0.0
board = teensymm
lib_extra_dirs = ../../CDJ_Libs, ../../MyLibs      ; For LVGL 9
;lib_extra_dirs = ../../CDJ_Libs                    ; For LVGL 8
lib_ignore = NativeEthernet
build_flags = -D LV_CONF_PATH="\"ian_lv_conf.h\""  ; For LVGL 9
              ;-D LV_CONF_INCLUDE_SIMPLE            ; For LVGL 8
              ;-D RDI_DEVELOPMENTS_REV3
              -D RDI_DEVELOPMENTS_DB5
              -D RDI_DEVELOPMENTS
              -D USB_DUAL_SERIAL
              ${common.build_flags}
board_build.f_cpu = 528000000L
monitor_port =  /dev/tty.usbmodem150283001
board_build.ldscript = linkerScript/RDI_v6_saveITCM_heapSDRAM_setOCRAM_4M_8M_NOCACHE.ld  

[env:beermat_t41]
platform_packages = platformio/framework-arduinoteensy @ symlink://../../framework-arduinoteensy-1.159
platform = teensy @ 5.0.0
board = teensy41
lib_extra_dirs = ../../CDJ_Libs, ../../MyLibs      ; For LVGL 9
;lib_extra_dirs = ../../CDJ_Libs                    ; For LVGL 8
lib_ignore = NativeEthernet
build_flags = -D LV_CONF_PATH="\"ian_lv_conf.h\""  ; For LVGL 9
              ;-D LV_CONF_INCLUDE_SIMPLE            ; For LVGL 8
              -D TEENSY41
              -D USB_DUAL_SERIAL
              ${common.build_flags}
board_build.f_cpu = 600000000L
;monitor_port = /dev/tty.usbmodem91441901   ;MacOS trigger 1
monitor_port =  /dev/tty.usbmodem90333101   ; MacOS trigger 3
;monitor_port =  /dev/tty.usbmodem83203701  ;MacOS trigger 4
board_build.ldscript = linkerScript/t41_v6_saveITCM_heapPSRAM_setOCRAM.ld  

[env:teensymm]
platform = https://github.com/platformio/platform-teensy.git
board = teensymm
lib_ignore = NativeEthernet
build_flags = ;-D LV_CONF_PATH="\"ian_lv_conf.h\"" ; For LVGL 9
              -D LV_CONF_INCLUDE_SIMPLE             ; For LVGL 8
              -D USB_DUAL_SERIAL
              ${common.build_flags}
board_build.f_cpu = 528000000L
;monitor_port =  /dev/cu.usbmodem*1 
;board_build.ldscript = linkerScript/imxrt1062_mm_db5_sqlite3.ld
board_build.ldscript = linkerScript/RDI_v6_saveITCM_heapSDRAM_setOCRAM_4M_8M_NOCACHE.ld  
;board_build.ldscript =  linkerScript/db5_sqlite3.ld


[common]
build_flags =
    -std=gnu++17                                     ; Add C++17
    -D TEENSY_OPT_FASTER                             ; -O2
    -D SQLITE_OS_OTHER=1
    -D SQLITE_THREADSAFE=0
    -D SQLITE_TEMP_STORE=3
    -D SQLITE_DEFAULT_MMAP_SIZE=0
    -D SQLITE_DEFAULT_MEMSTATUS=0
    -D SQLITE_MAX_EXPR_DEPTH=0
    -D SQLITE_DQS=0
    -D SQLITE_STRICT_SUBTYPE=1
    -D SQLITE_OMIT_DEPRECATED=1
    -D SQLITE_OMIT_SHARED_CACHE=1
    -D SQLITE_OMIT_PROGRESS_CALLBACK=1
    -D SQLITE_OMIT_AUTOINIT=1
    -D SQLITE_OMIT_DECLTYPE=1
    -D SQLITE_OMIT_LOAD_EXTENSION=1
    -D SQLITE_OMIT_UTF16=0
    -D SQLITE_OMIT_WAL=1
    -I config
    -Wl,--print-memory-usage                         ; Linker command to print memory region usage
    -g

[env]
framework = arduino
build_unflags = -std=gnu++14                         ; Remove C++14
monitor_filters = direct                             ; allows color code in serial output
